
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chost?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: ${dbuser:admi–∞s}
    password: ${dbpassword:rootpassword}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${CLIENT_ID:?Cant find client id}
            clientSecret: ${CLIENT_SECRET:?Cant find client secret}
            redirectUri: "http://localhost:9000/oauth2/callback/"
            scope:
              - email
              - profile

  servlet:
    multipart:
      max-file-size: 50MB
app:
  upload:
      path: ${UPLOAD_PATH:?Can`t find upload path}
  auth:
    secret: ${JWT_SECRET:Secret1234}
    token_expiration: 864000000
server:
  port: 9000
